name: gestion_restaurant  
type: web
env: php
plan: free
services:
  - type: web
    name: gestion-restaurant
    env: php
    version: 8.0.2  
    buildCommand: "composer install"  
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
