services:
  - type: web
    name: gestion-restaurant 
    env: php
    plan: free
    buildCommand: "composer install"  
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    runtime: "php:8.0.2"  
